(() => {
  const dictionaries = {
    en:{Home:"Home",Explore:"Explore",About:"About",Contribute:"Contribute",Login:"Login","Offline Mode":"Offline Mode","Online":"Online","Record locally":"Record locally","Sync now":"Sync now","Give a story a place in history.":"Give a story a place in history."},
    hi:{Home:"होम",Explore:"अन्वेषण",About:"परिचय",Contribute:"योगदान",Login:"लॉगिन","Offline Mode":"ऑफ़लाइन मोड",Online:"ऑनलाइन","Record locally":"स्थानीय रिकॉर्ड करें","Sync now":"अभी सिंक करें","Give a story a place in history.":"एक कहानी को इतिहास में स्थान दें।"},
    or:{Home:"ମୂଳପୃଷ୍ଠା",Explore:"ଅନ୍ୱେଷଣ",About:"ପରିଚୟ",Contribute:"ଅବଦାନ",Login:"ଲଗଇନ୍","Offline Mode":"ଅଫଲାଇନ୍ ମୋଡ୍",Online:"ଅନଲାଇନ୍","Record locally":"ସ୍ଥାନୀୟ ରେକର୍ଡ କରନ୍ତୁ","Sync now":"ଏବେ ସିଙ୍କ୍ କରନ୍ତୁ","Give a story a place in history.":"ଏକ କାହାଣୀକୁ ଇତିହାସରେ ସ୍ଥାନ ଦିଅନ୍ତୁ।"},
    bn:{Home:"হোম",Explore:"অন্বেষণ",About:"পরিচিতি",Contribute:"অবদান",Login:"লগইন","Offline Mode":"অফলাইন মোড",Online:"অনলাইন","Record locally":"স্থানীয়ভাবে রেকর্ড করুন","Sync now":"এখন সিঙ্ক করুন","Give a story a place in history.":"একটি গল্পকে ইতিহাসে স্থান দিন।"}
  };
  function selector(){if(document.getElementById('paramparaLanguageSelector'))return;const wrap=document.createElement('div');wrap.id='paramparaLanguageSelector';wrap.style='position:fixed;top:82px;right:18px;z-index:9998';wrap.innerHTML='<select aria-label="Language" style="padding:8px 11px;border-radius:999px;border:1px solid rgba(255,255,255,.14);background:rgba(15,12,10,.75);backdrop-filter:blur(14px);color:inherit"><option value="en">English</option><option value="hi">हिन्दी</option><option value="or">ଓଡ଼ିଆ</option><option value="bn">বাংলা</option></select>';document.body.appendChild(wrap);const select=wrap.querySelector('select');const saved=localStorage.getItem('parampara-language')||'en';select.value=saved;select.addEventListener('change',()=>apply(select.value));}
  function apply(lang){localStorage.setItem('parampara-language',lang);const dict=dictionaries[lang]||dictionaries.en;document.querySelectorAll('.nav-link,.login-btn,.mobile-menu a,.offline-action').forEach(el=>{const key=el.dataset.i18n||el.textContent.trim();if(dict[key]){el.dataset.i18n=key;const icon=el.querySelector('i');el.textContent=dict[key];if(icon)el.prepend(icon);}});const status=document.querySelector('.status-label');if(status&&!status.textContent.includes('·')){const key=status.textContent.trim();if(dict[key])status.textContent=dict[key];}}
  document.addEventListener('DOMContentLoaded',()=>{selector();apply(localStorage.getItem('parampara-language')||'en');});
})();
